# Generated by Django 6.0.2 on 2026-02-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bakery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('cuisine', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
