# Generated by Django 6.0.2 on 2026-02-21 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('image', models.URLField(blank=True, null=True)),
                ('bakery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakeries.bakery')),
            ],
        ),
    ]
